### ISSUE TITLE
你好，我按照你的步骤都安装成功了，怎么后台没有登陆的地方呢

### ISSUE THREAD

**Issue by baizhengliang** [Pad0y/Django2_dailyfresh#10]
![微信截图_20200819214014](https://user-images.githubusercontent.com/5041166/90642110-90131c80-e264-11ea-86a3-557c1d7978d4.png)
没看相关输入账号和密码的d地方，这是为什么呢，还是哪里做的不对

**Comment by Pad0y** [comment]
可能是因为网速的原因登陆界面没显示，刷新即可

**Comment by lingxicom** [comment]
![image](https://user-images.githubusercontent.com/48708610/91308105-67010780-e7e1-11ea-8018-925bad4cbd60.png)
没法解决啊

**Comment by Pad0y** [comment]
> ![image](https://user-images.githubusercontent.com/48708610/91308105-67010780-e7e1-11ea-8018-925bad4cbd60.png)
> 没法解决啊

具体是报了什么错误，说明具体原因

**Comment by lingxicom** [comment]
> > ![image](https://user-images.githubusercontent.com/48708610/91308105-67010780-e7e1-11ea-8018-925bad4cbd60.png)
> > 没法解决啊
> 
> 具体是报了什么错误，说明具体原因

![image](https://user-images.githubusercontent.com/48708610/91311612-daa51380-e7e5-11ea-8f84-037bbd6d3e62.png)

**Comment by Pad0y** [comment]
> > > ![image](https://user-images.githubusercontent.com/48708610/91308105-67010780-e7e1-11ea-8018-925bad4cbd60.png)
> > > 没法解决啊
> > 
> > 
> > 具体是报了什么错误，说明具体原因
> 
> ![image](https://user-images.githubusercontent.com/48708610/91311612-daa51380-e7e5-11ea-8f84-037bbd6d3e62.png)

现在无需手动构建，直接拉取镜像即可，详见README.md
