### ISSUE TITLE
商品，类别等图片都显示不出来

### ISSUE THREAD

**Issue by hellowbh** [Pad0y/Django2_dailyfresh#15]
为啥我运行后，除了 天天生鲜的logo外，增加的那些产品，类别等图片都显示不出？ 
右键看图片路径好像不对。
因为我是windows系统，所以把fdfs那句换成了本身的存储系统，难道是因为这个吗？
怎么改成不用fdfs也能显示图片？
您的setting.py里面我只把 第一行 改了
### DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
#Set fastdfs using the client of conf file path
#FDFS_CLIENT_CONF = '../utils/fdfs/client_deploy.conf'
FDFS_CLIENT_CONF = os.path.join(BASE_DIR, 'utils/fdfs/client_deploy.conf')
#Set IP:port

FDFS_STORAGE_URL = 'http://ip:port'  # fdfs服务器的ip和端口，注意端口是nginx的端口

**Comment by pumpkin-nbc** [comment]
现在行的通了吗

**Comment by zhousongyi** [comment]
> 现在行的通了吗

兄弟这个问题你搞定了吗？我被困扰还几天了

**Comment by zhousongyi** [comment]
> 为啥我运行后，除了 天天生鲜的logo外，增加的那些产品，类别等图片都显示不出？
> 右键看图片路径好像不对。
> 因为我是windows系统，所以把fdfs那句换成了本身的存储系统，难道是因为这个吗？
> 怎么改成不用fdfs也能显示图片？
> 您的setting.py里面我只把 第一行 改了
> 
> ### #DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'
> ### DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
> #Set fastdfs using the client of conf file path
> #FDFS_CLIENT_CONF = '../utils/fdfs/client_deploy.conf'
> FDFS_CLIENT_CONF = os.path.join(BASE_DIR, 'utils/fdfs/client_deploy.conf')
> #Set IP:port
> 
> FDFS_STORAGE_URL = 'http://ip:port' # fdfs服务器的ip和端口，注意端口是nginx的端口

兄弟这个问题你搞定了吗？我被困扰还几天了

**Comment by pumpkin-nbc** [comment]
图片是从服务器渲染过来的，所以需要自己去上传图片后再渲染。

**Comment by Pad0y** [comment]
详情搭建教程可以观看此视频：https://www.bilibili.com/video/BV1Xy4y1j71b @zhousongyi @hellowbh
