### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by George191** [Pad0y/Django2_dailyfresh#2]
authenticate 函数返回None  登陆失败  但是数据库中是有数据的
![H5F8BDpB](https://user-images.githubusercontent.com/41810038/66698245-c57adf80-ed0e-11e9-8e15-d088824717f1.png)
![wsv95NVL](https://user-images.githubusercontent.com/41810038/66698248-c7dd3980-ed0e-11e9-98a1-43821537fc4b.png)

**Comment by George191** [comment]
![yFXl6eXR](https://user-images.githubusercontent.com/41810038/66698264-f3602400-ed0e-11e9-9ab0-5d490d448b6e.png)

**Comment by Pad0y** [comment]
如果是通过注册写入到数据库的用户名需要激活，is_active字段需要为1。
注册功能是celery进行管理因此需要开启celery服务并且在setting里邮箱服务改为自己的配置

**Comment by Pad0y** [comment]
> 
> 
> ![yFXl6eXR](https://user-images.githubusercontent.com/41810038/66698264-f3602400-ed0e-11e9-9ab0-5d490d448b6e.png)



> 
> 
> authenticate 函数返回None 登陆失败 但是数据库中是有数据的
> ![H5F8BDpB](https://user-images.githubusercontent.com/41810038/66698245-c57adf80-ed0e-11e9-8e15-d088824717f1.png)
> ![wsv95NVL](https://user-images.githubusercontent.com/41810038/66698248-c7dd3980-ed0e-11e9-98a1-43821537fc4b.png)

如果是通过注册写入到数据库的用户名需要激活，is_active字段需要为1。
注册功能是celery进行管理因此需要开启celery服务并且在setting里邮箱服务改为自己的配置
